name: APK-J Build

on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
        with:
          fetch-depth: 0
      - name: Clone Project
     #  run: git clone -b main --depth=1 https://github.com/gjf026/dr0601.git
        run: git clone -b main --depth=1 https://github.com/gjf026/25041
     # - name: Setup Android SDK
    #    uses: android-actions/setup-android@v2
      #  with:
     #     sdk-version: 'commandlinetools-linux-8512546_latest'
  #    - name: Create local.properties
   #     run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Setup Python  
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' 

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found"
      - name: Modify pyramid——build.gradle
        working-directory: ./25041
        run: |
          # 替换Windows路径为系统Python路径
          sed -i '/buildPython("D:\/Programs\/Python\/Python38\/python.exe")/d' pyramid/build.gradle
          sed -i '$ s/^#//' ./gradle.properties
      - name: Setup Python local.properties
        working-directory: ./25041
        run: echo "" > local.properties    
      - name: DIY
        run: |
          chmod +x diy-J.sh
          bash ${{ github.workspace }}/diy-J.sh
      - name: Build With Gradle
        run: |
          num=$(find ${{ github.workspace }} -name gradlew  | awk -F"/" '{print NF-1}')
          DIR=$(find ${{ github.workspace }} -name gradlew  | cut -d \/ -f$num)
          cd $DIR
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" ${{ github.workspace }}/apk/
          done
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*
